### ISSUE TITLE
unexpected reserved word you may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by TolotraRam** [driftyco/ionic2-starter-tutorial#1]
Hi,

Got this error on gulp watch : 
www\app\app.js Line 1 : unexpected reserved word you may need an appropriate loader to handle this file type

**Comment by peterennis** [comment]
Same error.
Running on Windows 10.
Using PowerShell.

![capture14](https://cloud.githubusercontent.com/assets/140737/10266024/dd624c98-69fd-11e5-8875-972ddf8e9f4a.PNG)

**Comment by floatin** [comment]
me too.
