### ISSUE TITLE
Stupid question

### ISSUE THREAD

**Issue by gregor-srdic** [driftyco/ionic2-starter-tutorial#10]
I am new to typescript and this project is a bit confusing to me. Why are files with typescript source code, such as www/app/hello-ionic/hello.ionic.js of type .js not .ts? My WebStorm editor therefore assumes it's plain javascript and fails source code validation. 
Thanks!

**Comment by mhartington** [comment]
That file in particular is regular JavaScript/ES6 code. This project doesn't have any typescript code in it.
