### ISSUE TITLE
Whatever Happened to Mike Harrington?

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic2-starter-tutorial#16]
Lost - One Cute Puppy

From here:
http://ionicframework.com/docs/v2/getting-started/installation/

The app shows:

![capture14](https://cloud.githubusercontent.com/assets/140737/11200224/fc1ed342-8c88-11e5-8580-bb017cb13145.PNG)

This link is OK:
https://pbs.twimg.com/profile_images/598205061232103424/3j5HUXMY.png
This link is bad:
https://pbs.twimg.com/profile_images/578237281384841216/R3ae1n61.png

They are also referenced here:
http://angular-meteor.com/tutorials/ionic/server

**Comment by mhartington** [comment]
Damn, thats what I get for changing my twitter picture.

**Comment by peterennis** [comment]
Mike Harrington vs. mhartington
Is there a typo somewhere?

**Comment by mhartington** [comment]
There all parody names, so they're not our real name.
