### ISSUE TITLE
browser-sync Windows inconvenience

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic2-starter-tutorial#7]
Both this project and ionic (2) alpha depend on browser-sync.
That one being dependent on node-gyp causes a problem for users on Windows. You need Python, Visual Studio and what not. Unless you don't have all that in place you end up with a broken browser-sync installation and a malfunctioning ionic 2 development flow.

http://www.browsersync.io/docs/#windows-users

Isn't there any better alternative?

**Comment by mhartington** [comment]
Just following up on this. Yes, we're replacing browser-sync with a smaller and easier live reload server. Same one that is in ionic 1

**Comment by zarko-tg** [comment]
Thanks boss, good to hear!
